language: go

go: 1.11

notifications:
    email: false

env:
    - PATH=$HOME/gopath/bin:$PATH
    - QUICK_TEST_SEED=0

install:
    - go get github.com/golang/lint/golint
    - go get github.com/fzipp/gocyclo
    - go get github.com/gordonklaus/ineffassign
    - go get github.com/client9/misspell/cmd/misspell
    - go get -t -v ./... && go build -v ./...

script:
    - ./gok.sh
